### ISSUE TITLE
CREO2URDF – Use the OTK for getting the relevant information for the urdf

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/creo2urdf#13]
### Task description
This is the follow-up of #11.

We would like to:
- [x] Extract info about the axis
- [x] Extract info about the transformation between links
- [x] Extract mass and inertia moment info of links
- [x] Start using idyntree

### Definition of done
The above list is completed
