### ISSUE TITLE
CREO2URDF – Validation of MVP-1

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/creo2urdf#16]
### Task description

This is a follow-up of #13.

- [x] Validate the urdf obtained in #13 
  - [x] Visualize the model with `idyntree-visualizer`
    - [x]  Check if the visual/collision are correctly exported
    - [x]  Check that kinematics info is correct
  - [x] As @traversaro suggested: https://github.com/icub-tech-iit/creo2urdf/issues/13#issuecomment-1506681619	
  - [x] Compare total inertial properties get from idyntree and from Creo.

**Optional**:
- [ ] Get the rest position from Creo and set it in the `iDynTree::RevoluteJoint`
- [ ] Get the joints limits from Creo and set it in the `iDynTree::RevoluteJoint`
- [ ] Align stl path as we manage in other urdf with relative/package path
- [ ] Add a gazebo control board in the resulting urdf
- [ ] Generate `protk.dat` via cmake with the correct paths

### Definition of done

The above list is completed

cc @pattacini
